version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./images:/usr/share/nginx/images
      - ./Conf/nginx.conf:/etc/nginx.conf:ro
    restart: unless-stopped